import type {
  BlueprintBrief,
  EvidenceItem,
  BusinessRuleDefinition,
  DataEntityDefinition,
  DataFieldDefinition,
  IntegrationDefinition,
  ModuleDefinition,
  NotificationRule,
  PersonaDefinition,
  ScreenDefinition,
  ScreenUISpec,
  UserJourneyDefinition,
  ValidationRule,
} from "../src/types";
import {
  ANCHOR,
  DAY,
  DEFAULT_OPERATOR,
  PATTERN,
  PEOPLE,
  ORGS,
  blueprintEntities,
  blueprintIntegrations,
  blueprintJourneys,
  blueprintNotifications,
  blueprintPersonas,
  blueprintRules,
  blueprintScreens,
  blueprintValidations,
  buildScreenUI,
  codePrefix,
  deriveOperatorRole,
  deriveSubject,
  fmtDate,
  plural,
  rng,
  sampleTable,
} from "./blueprint";
import { parseBrief } from "./briefParser";

/**
 * Everything the local engine predicts for a product, in one bundle.
 *
 * When the brief describes a process ("A → B → C"), the product is built around
 * that process: one lifecycle state per stage, a work screen per stage group, a
 * 360 view with the stage-by-stage proof of record, and the parties and parts the
 * brief names. Otherwise the generic capture-work-oversee blueprint is used.
 * No domain knowledge: every stage, party and part name comes from the brief.
 */
export interface Blueprint {
  subject: string;
  operator: string;
  brief: BlueprintBrief;
  personas: PersonaDefinition[];
  modules: ModuleDefinition[];
  screens: ScreenDefinition[];
  userJourneys: UserJourneyDefinition[];
  businessRules: BusinessRuleDefinition[];
  dataEntities: DataEntityDefinition[];
  integrations: IntegrationDefinition[];
  notifications: NotificationRule[];
  validations: ValidationRule[];
}

const HOLD = "On Hold";
const CANCELLED = "Cancelled";
const MAX_STAGE_SCREENS = 8;

const inferred = <T extends object>(item: T, pattern: string) =>
  ({ ...item, confidence: "INFERRED" as const, evidence: [PATTERN(pattern)] });

/** The brief's main user: the role named after "for", else the first party the brief mentions. */
function pickOperator(productName: string, description: string, brief: BlueprintBrief): string | undefined {
  const named = deriveOperatorRole(productName, description);
  if (named) return named;
  const inName = brief.parties.find((p) => new RegExp(`\\b${p.replace(/[^A-Za-z0-9]/g, "")}s?\\b`, "i").test(productName));
  return inName ?? brief.parties[0];
}

export function buildBlueprint(productName: string, businessUnit: string, briefText: string, known?: BlueprintBrief): Blueprint {
  const brief = known ?? parseBrief(briefText, productName);
  const subject = brief.subject ?? deriveSubject(productName, businessUnit);
  const operator = pickOperator(productName, briefText, brief) ?? DEFAULT_OPERATOR;
  if (brief.stages.length >= 3) return processBlueprint(productName, subject, operator, brief);

  const { modules, screens } = blueprintScreens(subject);
  return {
    subject, operator, brief,
    personas: blueprintPersonas(subject, operator),
    modules, screens,
    userJourneys: blueprintJourneys(subject, operator),
    businessRules: blueprintRules(subject),
    dataEntities: blueprintEntities(subject),
    integrations: blueprintIntegrations(),
    notifications: blueprintNotifications(subject, operator),
    validations: blueprintValidations(subject),
  };
}

/** Split stages into at most `max` contiguous groups, earlier groups taking the extra stage. */
function groupStages(stages: string[], max: number): string[][] {
  const n = Math.min(max, stages.length);
  const groups: string[][] = [];
  let i = 0;
  for (let g = 0; g < n; g++) {
    const size = Math.floor(stages.length / n) + (g < stages.length % n ? 1 : 0);
    groups.push(stages.slice(i, i + size));
    i += size;
  }
  return groups;
}

function processEntities(subject: string, stages: string[], brief: BlueprintBrief): DataEntityDefinition[] {
  const prefix = codePrefix(subject);
  const f = (name: string, type: string, required: boolean, notes: string, constraints: DataFieldDefinition["constraints"] = {}): DataFieldDefinition =>
    ({ name, type, required, notes, constraints, origin: "INFERRED" });
  const states = [...stages, HOLD, CANCELLED];
  const transitions = [
    ...stages.slice(0, -1).map((s, i) => ({ from: s, to: stages[i + 1] })),
    ...stages.slice(0, -1).map((s) => ({ from: s, to: HOLD })),
    ...stages.slice(0, -1).map((s) => ({ from: HOLD, to: s })),
    ...stages.slice(0, Math.ceil(stages.length / 2)).map((s) => ({ from: s, to: CANCELLED })),
  ];
  const parties = brief.parties;
  const main: DataEntityDefinition = {
    id: "ent-bp-1",
    name: subject,
    description: `The ${subject.toLowerCase()} tracked end to end: ${stages.join(" → ")}.`,
    fields: [
      { ...f("referenceNumber", "string", true, "Business key, generated by the system and shown on every document", { format: "identifier", pattern: `^${prefix}-[0-9]{4,8}$`, maxLength: 20, unique: true, immutable: true }), source: "system" },
      f("title", "string", true, "Short summary a reviewer can scan", { format: "text", minLength: 5, maxLength: 120 }),
      f("organization", "string", true, "Organisation the record belongs to", { format: "text", maxLength: 120 }),
      ...(parties.length >= 2 ? [f("responsibleParty", "enum", true, "Party responsible for the current stage", { format: "enum", enumValues: parties })] : []),
      f("priority", "enum", true, "Drives queue order and SLA", { format: "enum", enumValues: ["LOW", "MEDIUM", "HIGH", "CRITICAL"] }),
      f("contactEmail", "string", true, "Who receives stage updates", { format: "email", maxLength: 254, sensitivity: "pii" }),
      f("assignee", "string", false, "Person working the current stage", { format: "text", maxLength: 80 }),
      f("dueDate", "date", false, "Target date for the current stage", { format: "date" }),
      f("estimatedValue", "decimal", false, "Monetary value at stake, if any", { format: "decimal", min: 0, max: 100_000_000, precision: 2, sensitivity: "financial" }),
      f("description", "text", false, "Full context", { format: "free-text", maxLength: 4000 }),
      f("holdReason", "text", false, "Why the record is on hold or cancelled", { format: "free-text", maxLength: 2000 }),
      f("status", "enum", true, "Current lifecycle stage", { format: "enum", enumValues: states }),
    ],
    lifecycle: { statusField: "status", states, initial: stages[0], transitions },
    rules: [
      { id: "bp-r1", kind: "conditional", when: { field: "status", op: "eq", value: HOLD }, effect: "required", target: "holdReason", message: "Say what the record is waiting for.", origin: "INFERRED" },
      { id: "bp-r2", kind: "conditional", when: { field: "status", op: "eq", value: CANCELLED }, effect: "required", target: "holdReason", message: "Give a reason before cancelling.", origin: "INFERRED" },
      { id: "bp-r3", kind: "conditional", when: { field: "priority", op: "eq", value: "CRITICAL" }, effect: "required", target: "dueDate", message: "Critical items need a due date.", origin: "INFERRED" },
    ],
    crossRecordRules: [
      "referenceNumber is unique across all records and is generated by the system.",
      `A ${subject.toLowerCase()} moves to the next stage only when the current stage has a completed stage record.`,
      "assignee must be an active user of the party responsible for the current stage.",
    ],
    relationships: [`${subject} Stage Record (1:N)`, ...(brief.parts ? [`${brief.parts.name} (1:N)`] : []), "Attachment (1:N)"],
    confidence: "INFERRED",
    evidence: [PATTERN(`lifecycle taken from the brief: ${stages.join(" → ")}`)],
  };
  const stageRecord: DataEntityDefinition = {
    id: "ent-bp-2",
    name: `${subject} Stage Record`,
    description: `Proof of record: who completed each stage of a ${subject.toLowerCase()}, when, and with what evidence. Append-only.`,
    fields: [
      f("subjectReference", "string", true, `Reference of the ${subject.toLowerCase()}`, { format: "identifier", maxLength: 20, immutable: true }),
      f("stage", "enum", true, "Stage completed", { format: "enum", enumValues: stages, immutable: true }),
      f("completedAt", "datetime", true, "When the stage was completed", { format: "datetime", immutable: true }),
      f("completedByEmail", "string", true, "Who completed it", { format: "email", maxLength: 254, sensitivity: "pii", immutable: true }),
      ...(parties.length ? [f("party", "string", true, "Organisation that completed the stage", { format: "text", maxLength: 120 })] : []),
      f("evidenceUrl", "string", false, "Document, photo or certificate proving the stage", { format: "url", maxLength: 500 }),
      f("notes", "text", false, "Observations", { format: "free-text", maxLength: 2000 }),
    ],
    crossRecordRules: ["subjectReference must point to an existing record.", "Stage records are never edited or deleted; corrections are new records."],
    relationships: [`${subject} (N:1)`],
    confidence: "INFERRED",
    evidence: [PATTERN("append-only proof-of-record per stage")],
  };
  const entities = [main, stageRecord];
  if (brief.parts) {
    const partTypes = brief.parts.types.map((t) => t.toUpperCase().replace(/[^A-Z0-9]+/g, "_"));
    entities.push({
      id: "ent-bp-3",
      name: brief.parts.name,
      description: `${plural(brief.parts.name)} of a ${subject.toLowerCase()} (${brief.parts.types.join(", ")}), each traceable by serial number.`,
      fields: [
        f("serialNumber", "string", true, "Unique serial number", { format: "identifier", minLength: 4, maxLength: 40, unique: true, immutable: true }),
        f(`${brief.parts.name.charAt(0).toLowerCase()}${brief.parts.name.slice(1).replace(/\s+/g, "")}Type`, "enum", true, "Kind of part", { format: "enum", enumValues: partTypes }),
        f("subjectReference", "string", true, `${subject} this part is fitted to`, { format: "identifier", maxLength: 20 }),
        f("supplier", "string", true, "Who supplied the part", { format: "text", maxLength: 120 }),
        f("receivedDate", "date", false, "When it was received", { format: "date" }),
        f("fittedDate", "date", false, "When it was fitted", { format: "date" }),
      ],
      rules: [{ id: "bp-p1", kind: "compare", left: "receivedDate", op: "lte", right: "fittedDate", message: "A part cannot be fitted before it is received.", origin: "INFERRED" }],
      crossRecordRules: [`serialNumber is unique across all ${plural(brief.parts.name).toLowerCase()}.`, `A ${brief.parts.name.toLowerCase()} is fitted to at most one ${subject.toLowerCase()} at a time.`],
      relationships: [`${subject} (N:1)`],
      confidence: "INFERRED",
      evidence: [PATTERN(`parts list taken from the brief: ${brief.parts.types.join(", ")}`)],
    });
  }
  return entities;
}

function processPersonas(subject: string, operator: string, brief: BlueprintBrief): PersonaDefinition[] {
  const s = subject.toLowerCase();
  const parties = [operator, ...brief.parties.filter((p) => p !== operator)].slice(0, 4);
  const partyPersonas = parties.map((p, i) =>
    inferred({
      id: `p-bp-party-${i + 1}`,
      name: p,
      role: p,
      keyGoals: [i === 0 ? `Run their ${plural(s)} through every stage they own` : `Complete their stages of each ${s} on time`, `See the full history of every ${s} they touch`],
      permissions: ["Read/Write own records", "Complete owned stages"],
    }, "party named in the brief")
  );
  return [
    ...partyPersonas,
    inferred({ id: "p-bp-3", name: "Operations Lead", role: "Approver", keyGoals: ["Unblock stalled records", "Protect stage SLAs across all parties"], permissions: ["Approve", "Reassign", "View all dashboards"] }, "approver and team-lead role"),
    inferred({ id: "p-bp-4", name: "Platform Administrator", role: "Administrator", keyGoals: ["Configure stages, SLAs and party access", "Manage users and roles"], permissions: ["Full Administrative Access"] }, "administrator role"),
    inferred({ id: "p-bp-5", name: "Compliance Auditor", role: "Auditor", keyGoals: [`Trace every ${s} from first to last stage`, "Export the proof of record"], permissions: ["Read Only", "Audit Logs"] }, "independent read-only audit role"),
  ];
}

const STAGE_NOTE = (label: string, prev?: string, next?: string) =>
  `Stage workbench built from your lifecycle: records at "${label}"${prev ? `, received from "${prev}"` : ""}${next ? `, handed to "${next}"` : ""}. Mirrors the queue-per-stage pattern of leading lifecycle products.`;

function stageUI(subject: string, entity: DataEntityDefinition, group: string[], stages: string[], seed: string, layout: ScreenDefinition["layoutType"], owner?: string): ScreenUISpec {
  const first = group[0], last = group[group.length - 1];
  const idx = stages.indexOf(last);
  const prev = stages[stages.indexOf(first) - 1];
  const next = stages[idx + 1];
  const rand = rng(`${seed}|kpi`);
  const table = sampleTable(entity, subject, seed, 7, [...group, ...group, ...(next ? [next] : []), HOLD]);
  const statusIdx = table.columns.length - 1;
  const at = 12 + Math.floor(rand() * 60);
  const overdue = Math.floor(rand() * 8) + 1;
  const sel = table.rows[0];
  return {
    kpis: [
      { label: `At ${first}${group.length > 1 ? ` – ${last}` : ""}`, value: String(at), trend: "up", delta: `+${Math.ceil(rand() * 6)} since yesterday` },
      { label: "Overdue", value: String(overdue), trend: overdue > 4 ? "up" : "down", delta: "Past stage SLA" },
      { label: "Avg Days in Stage", value: (0.8 + rand() * 4).toFixed(1), trend: "down", delta: "-0.4 vs last month" },
      { label: next ? `Moved to ${next}` : "Completed This Week", value: String(5 + Math.floor(rand() * 30)), trend: "up", delta: "This week" },
    ],
    filters: ["All", ...group, ...(next ? [next] : []), HOLD].filter((v, i, a) => a.indexOf(v) === i).slice(0, 5),
    table: { title: `${plural(subject)} at ${group.join(" / ")}`, ...table },
    detailPanels: [
      { title: `${subject} Summary`, items: table.columns.slice(1, 5).map((label, i) => ({ label, value: sel[i + 1] })) },
      {
        title: "Stage Hand-off",
        items: [
          ...(prev ? [{ label: "Received from", value: `${prev} · ${fmtDate(ANCHOR - 2 * DAY)}` }] : [{ label: "Entry point", value: "First stage" }]),
          { label: "Current stage", value: sel[statusIdx] },
          ...(next ? [{ label: "Hands off to", value: next }] : [{ label: "Exit", value: `${subject} closed` }]),
          ...(owner ? [{ label: "Stage owner", value: owner }] : []),
        ],
      },
      {
        title: "Proof of Record",
        items: [
          { label: "Completed by", value: PEOPLE[3] },
          { label: "Evidence", value: "2 documents attached" },
          { label: "Time stamp", value: `${fmtDate(ANCHOR - DAY)} 14:30` },
        ],
      },
    ],
    primaryActions: [next ? `Complete ${last} → ${next}` : `Complete ${last}`, "Attach Evidence", "Put On Hold", "Reassign"],
    benchmarkNote: STAGE_NOTE(group.join(" / "), prev, next),
    ...(layout === "form-wizard" ? { entity: entity.name } : {}),
  };
}

function processBlueprint(productName: string, subject: string, operator: string, brief: BlueprintBrief): Blueprint {
  const stages = brief.stages;
  const s = subject.toLowerCase();
  const S = plural(subject);
  const entities = processEntities(subject, stages, brief);
  const [main] = entities;
  const personas = processPersonas(subject, operator, brief);
  const parties = personas.filter((p) => p.id.startsWith("p-bp-party-")).map((p) => p.name);
  const seed = productName;
  const rand = rng(`${seed}|overview`);

  // Stage groups -> work screens; phases (three groups) -> modules.
  const groups = groupStages(stages.slice(1), MAX_STAGE_SCREENS);
  const phases = groupStages(stages, Math.min(3, stages.length));
  const phaseOf = (stage: string) => phases.findIndex((p) => p.includes(stage));
  const phaseName = (p: string[]) => (p.length > 1 ? `${p[0]} → ${p[p.length - 1]}` : p[0]);
  const ownerOf = (stage: string) => (parties.length ? parties[phaseOf(stage) % parties.length] : undefined);

  const counts = stages.map(() => 4 + Math.floor(rand() * 40));
  const overview: ScreenUISpec = {
    kpis: [
      { label: `Active ${S}`, value: counts.reduce((a, b) => a + b, 0).toLocaleString("en-US"), trend: "up", delta: `+${(2 + rand() * 5).toFixed(1)}% vs last month` },
      { label: "Stalled Beyond SLA", value: String(3 + Math.floor(rand() * 15)), trend: "down", delta: `-${Math.ceil(rand() * 4)} vs last week` },
      { label: "Avg End-to-End Days", value: (10 + rand() * 30).toFixed(1), trend: "down", delta: "-1.8 days vs last quarter" },
      { label: `Reached ${stages[stages.length - 1]}`, value: String(counts[counts.length - 1]), trend: "flat", delta: "This month" },
    ],
    filters: ["All", ...stages.slice(0, 3), HOLD],
    table: { title: `${S} Needing Attention`, ...sampleTable(main, subject, `${seed}|overview`, 7, [stages[1], stages[Math.floor(stages.length / 2)], HOLD, stages[stages.length - 2], stages[0], stages[2], stages[stages.length - 1]]) },
    detailPanels: [
      { title: "Records per Stage", items: stages.map((st, i) => ({ label: st, value: String(counts[i]) })) },
      { title: "Stage Owners", items: phases.map((p) => ({ label: phaseName(p), value: ownerOf(p[0]) ?? "Operations Lead" })) },
    ],
    primaryActions: ["Review Stalled Records", "Export Pipeline", "Share Snapshot"],
    benchmarkNote: `Command center for the ${stages.length}-stage lifecycle in your brief. Mirrors the pipeline-overview pattern of leading lifecycle products.`,
  };

  const current = Math.min(stages.length - 2, Math.max(2, Math.floor(stages.length * 0.6)));
  const timeline = stages.map((st, i) => ({
    label: st,
    value: i < current ? `✓ ${fmtDate(ANCHOR - (current - i) * 3 * DAY)} · ${ownerOf(st) ?? PEOPLE[i % PEOPLE.length]}` : i === current ? "In Progress" : "Pending",
  }));
  const records360 = sampleTable(main, subject, `${seed}|360`, 7, [stages[current], stages[current - 1], stages[current + 1], stages[current], HOLD, stages[current - 2], stages[current]]);
  const first360 = records360.rows[0];
  const record360: ScreenUISpec = {
    kpis: [
      { label: "Current Stage", value: stages[current], trend: "flat", delta: `${current} of ${stages.length} stages done` },
      { label: "Days Since Start", value: String(current * 3 + 2), trend: "up", delta: "Target 30 days" },
      { label: "Open Issues", value: String(Math.floor(rand() * 3)), trend: "down", delta: "Across all parties" },
    ],
    filters: ["All", stages[current], stages[current - 1], stages[current + 1]],
    // The header shows the selected row, so the table lists the records; the timeline panel is the proof of record.
    table: { title: `All ${S}`, ...records360 },
    detailPanels: [
      { title: "Lifecycle Timeline", items: timeline },
      ...(brief.parts ? [{ title: `${plural(brief.parts.name)} (by serial number)`, items: brief.parts.types.map((t, i) => ({ label: t, value: `${t.replace(/[^A-Za-z]/g, "").slice(0, 3).toUpperCase()}-${240_117 + i * 389}` })) }] : []),
      // Summary of the record selected by default (the first row), so header and panel agree.
      { title: `${subject} Summary`, items: records360.columns.map((label, i) => ({ label, value: first360[i] })).slice(0, 5) },
    ],
    primaryActions: [`Complete ${stages[current]}`, "Attach Evidence", "Export Proof of Record"],
    benchmarkNote: `One page per ${s}: every stage of your lifecycle with who, when and evidence${brief.parts ? `, plus its ${plural(brief.parts.name).toLowerCase()} by serial number` : ""}. Mirrors the 360-degree record view of leading products.`,
  };

  const perf: ScreenUISpec = {
    kpis: [
      { label: "Throughput", value: `${40 + Math.floor(rand() * 80)} / week`, trend: "up", delta: "+6% vs last month" },
      { label: "Within Stage SLA", value: `${(86 + rand() * 10).toFixed(1)}%`, trend: "up", delta: "Target 95%" },
      { label: "Slowest Stage", value: stages[1 + Math.floor(rand() * (stages.length - 2))], trend: "flat", delta: "Avg 4.6 days" },
      { label: "Rework Rate", value: `${(1 + rand() * 4).toFixed(1)}%`, trend: "down", delta: "-0.6 pts" },
    ],
    filters: ["All", "On Track", "At Risk", "Breached"],
    table: {
      title: "Stage Performance",
      columns: ["Stage", "Owner", "In Stage", "Avg Days", "Within SLA", "Status"],
      rows: stages.map((st, i) => {
        const sla = 82 + ((i * 7 + 3) % 17);
        return [st, ownerOf(st) ?? "Operations Lead", String(counts[i]), (0.6 + ((i * 13) % 40) / 10).toFixed(1), `${sla}%`, sla >= 95 ? "On Track" : sla >= 88 ? "At Risk" : "Breached"];
      }),
    },
    detailPanels: [
      { title: "Bottlenecks", items: stages.slice(1, 4).map((st, i) => ({ label: st, value: `${3 + i} stalled > SLA` })) },
      { title: "By Party", items: (parties.length ? parties : ["Operations Lead"]).map((p, i) => ({ label: p, value: `${(88 + i * 2.5).toFixed(1)}% within SLA` })) },
    ],
    primaryActions: ["Export Report", "Adjust Stage SLAs"],
    benchmarkNote: "Per-stage throughput and SLA for your lifecycle. Mirrors the operational analytics pattern of leading products.",
  };

  const first = stages[0];
  const intake = buildScreenUI({ id: "scr-bp-intake", name: `New ${first}`, layoutType: "form-wizard" }, main, subject, seed);
  intake.table = { ...intake.table, title: `Recent ${first} Records` };
  intake.primaryActions = [`Submit ${first}`, "Save Draft"];
  intake.benchmarkNote = `Capture for "${first}", the first stage of your lifecycle; the record then moves to "${stages[1]}". Mirrors the guided-intake pattern of top self-service products.`;

  const phaseModules = phases.map((p, i) => ({ id: `mod-bp-phase-${i + 1}`, name: phaseName(p) }));
  const moduleFor = (stage: string) => phaseModules[phaseOf(stage)].name;
  const oversight = "Oversight & Traceability";

  const screens: ScreenDefinition[] = [
    inferred({ id: "scr-bp-1", name: `${subject} Command Center`, module: oversight, layoutType: "dashboard" as const, components: ["KPI tiles", "Records per stage", "Stalled records"], purpose: `See every ${s} across all ${stages.length} stages and what is stalled.`, ui: overview }, "pipeline command center"),
    inferred({ id: "scr-bp-intake", name: `New ${first}`, module: moduleFor(first), layoutType: "form-wizard" as const, components: ["Stepper", "Validated fields", "Review & submit"], purpose: `Capture a complete ${first.toLowerCase()} the first time.`, ui: intake }, "guided intake for the first stage"),
    ...groups.map((g, i) => {
      const layout = (i % 2 === 0 ? "split-view" : "table-detail") as ScreenDefinition["layoutType"];
      return inferred({
        id: `scr-bp-stage-${i + 1}`,
        name: g.join(" + "),
        module: moduleFor(g[0]),
        layoutType: layout,
        components: ["Stage queue", "Hand-off details", "Proof of record"],
        purpose: `Work ${plural(s)} at ${g.join(" and ")}${ownerOf(g[0]) ? ` (owned by ${ownerOf(g[0])})` : ""} and hand them to the next stage.`,
        ui: stageUI(subject, main, g, stages, `${seed}|stage-${i}`, layout, ownerOf(g[0])),
      }, `work queue for the "${g.join(" / ")}" stage`);
    }),
    inferred({ id: "scr-bp-5", name: `${subject} 360`, module: oversight, layoutType: "profile-360" as const, components: ["Lifecycle timeline", "Proof of record", ...(brief.parts ? [`${plural(brief.parts.name)} by serial`] : [])], purpose: `Everything about one ${s}: each stage, who completed it, when, and the evidence.`, ui: record360 }, "360-degree record view with proof of record"),
    inferred({ id: "scr-bp-6", name: "Lifecycle Performance", module: oversight, layoutType: "dashboard" as const, components: ["Throughput", "Stage SLA", "Bottlenecks"], purpose: "Measure throughput and SLA per stage and per party.", ui: perf }, "operational analytics dashboard"),
  ];

  const modules: ModuleDefinition[] = [
    ...phaseModules.map((m, i) => inferred({ ...m, description: `Stages ${phases[i].join(" → ")}.`, screens: screens.filter((sc) => sc.module === m.name).map((sc) => sc.id) }, "lifecycle phase from the brief")),
    inferred({ id: "mod-bp-oversight", name: oversight, description: `Command center, ${subject} 360 and performance across the whole lifecycle.`, screens: screens.filter((sc) => sc.module === oversight).map((sc) => sc.id) }, "oversight and traceability module"),
  ];

  const userJourneys: UserJourneyDefinition[] = [
    inferred({ id: "uj-bp-1", name: `End-to-end ${s} lifecycle`, persona: operator, steps: stages.map((st) => `${st}${ownerOf(st) ? ` (${ownerOf(st)})` : ""}`), outcome: `Every ${s} reaches "${stages[stages.length - 1]}" with a complete proof of record.` }, "lifecycle from the brief"),
    ...phases.map((p, i) => inferred({
      id: `uj-bp-phase-${i + 1}`,
      name: phaseName(p),
      persona: ownerOf(p[0]) ?? operator,
      steps: [`Open ${p[0]} queue`, ...p.map((st) => `Complete ${st} and attach evidence`), p === phases[phases.length - 1] ? `Close the ${s}` : `Hand off to ${stages[stages.indexOf(p[p.length - 1]) + 1]}`],
      outcome: `Stages ${phaseName(p)} completed on time and on record.`,
    }, "phase journey")),
    inferred({ id: "uj-bp-trace", name: `Trace a ${s}`, persona: "Compliance Auditor", steps: [`Search the ${s} by reference`, `Open ${subject} 360`, "Review each stage's who, when and evidence", ...(brief.parts ? [`Check ${plural(brief.parts.name).toLowerCase()} by serial number`] : []), "Export the proof of record"], outcome: "Any question about the record is answered from one page." }, "audit trace journey"),
  ];

  const rule = (rule: string, context: string, pattern: string) => ({ rule, context, pattern });
  const rules = [
    rule(`Stages run in order: ${stages.join(" → ")}. A stage cannot be skipped or completed twice.`, "Lifecycle", "stage-gate sequence"),
    rule("Every stage completion records who completed it, when, and at least one piece of evidence (proof of record).", "Traceability", "proof of record"),
    ...(brief.parts ? [rule(`Each ${brief.parts.name.toLowerCase()} serial number is unique and fitted to at most one ${s} at a time.`, "Traceability", "serialised parts")] : []),
    rule("Putting a record on hold or cancelling it requires a reason; cancelling is allowed only in the first half of the lifecycle.", "Decisions", "justified exceptions"),
    ...(parties.length >= 2 ? [rule("Each party sees and edits only the records and stages it is responsible for.", "Access", "party-scoped access")] : []),
    rule("Records past 80% of a stage SLA are flagged at risk and escalated to the Operations Lead at 100%.", "SLA", "SLA escalation"),
    rule("Personal and financial fields are masked for roles without a need to know.", "Privacy", "least-privilege data access"),
  ];
  const businessRules: BusinessRuleDefinition[] = rules.map((r, i) =>
    inferred({ id: `br-bp-${i + 1}`, code: `BR-${String(i + 1).padStart(3, "0")}`, rule: r.rule, context: r.context }, r.pattern)
  );

  const integrations = [
    ...blueprintIntegrations(),
    ...(parties.length >= 2 ? [inferred({ id: "int-bp-5", system: `Partner Access (${parties.join(", ")})`, protocol: "Portal SSO / REST API", purpose: "Let each party complete its stages and exchange records" }, "multi-party access")] : []),
  ];

  const notifications: NotificationRule[] = [
    ...stages.slice(0, -1).filter((_, i) => i % Math.max(1, Math.floor(stages.length / 4)) === 0).map((st) => {
      const nxt = stages[stages.indexOf(st) + 1];
      return { event: `${st} completed`, channel: "In-App & Email", recipient: ownerOf(nxt) ?? "Operations Lead" };
    }),
    { event: "Stage SLA at risk (80%)", channel: "In-App & Email", recipient: "Operations Lead" },
    { event: `${subject} put on hold`, channel: "Email", recipient: operator },
  ];

  return {
    subject, operator, brief, personas, modules, screens, userJourneys, businessRules,
    dataEntities: entities,
    integrations,
    notifications,
    validations: [
      ...blueprintValidations(subject).filter((v) => !/decisionReason|requesterEmail/.test(v.field)),
      { field: "status", validationRule: `Moves only to the next stage (${stages.slice(0, 3).join(" → ")} …), On Hold or, early on, Cancelled`, errorMessage: "That stage change is not allowed from the current stage." },
      { field: "holdReason", validationRule: "Required when status is On Hold or Cancelled", errorMessage: "Give a reason." },
      ...(brief.parts ? [{ field: "serialNumber", validationRule: "Required, 4 to 40 characters, unique", errorMessage: "Enter the part's serial number." }] : []),
    ],
  };
}

/** The blueprint as understanding items, so the Business Understanding screen is filled too. */
export function blueprintToUnderstanding(bp: Blueprint): Record<"personas" | "modules" | "screens" | "userJourneys" | "businessRules" | "dataEntities" | "integrations", EvidenceItem[]> {
  const item = (id: string, title: string, description: string, evidence: string[]): EvidenceItem =>
    ({ id, title, description, status: "INFERRED", evidenceReferences: evidence });
  return {
    personas: bp.personas.map((p) => item(p.id, p.name, `${p.keyGoals.join(". ")}.`, p.evidence)),
    modules: bp.modules.map((m) => item(m.id, m.name, m.description, m.evidence)),
    screens: bp.screens.map((s) => item(s.id, s.name, s.purpose, s.evidence)),
    userJourneys: bp.userJourneys.map((j) => item(j.id, j.name, `${j.steps.join(" → ")}. ${j.outcome}`, j.evidence)),
    businessRules: bp.businessRules.map((r) => item(r.id, `${r.code}: ${r.context}`, r.rule, r.evidence)),
    dataEntities: bp.dataEntities.map((e) => ({ ...item(e.id, e.name, e.description, e.evidence), fields: e.fields })),
    integrations: bp.integrations.map((i) => item(i.id, i.system, `${i.purpose} (${i.protocol})`, i.evidence)),
  };
}
